---
dist: xenial
addons:
  apt:
    packages:
      - graphviz

sudo: required

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  - node_modules

before_install:
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
  - sudo apt install nodejs
  - npm install decktape


after_success:
  - cd target/generated-slides
  - git init
  - git config user.name "${Sharabarin}"
  - git config user.email "${sharabarin@email.cz}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${Access public repositories}@${https://sharabarin.github.io}" master:gh-pages > /dev/null 2>&1
